### ISSUE TITLE
can't install/run vcf

### ISSUE THREAD

**Issue by linuxcaffe** [l0b0/vcf#1]
can't seem to get it going.
tried 
git submodules init
and 
git submodules update
but then
djp@tigger:~/tmp/vcf$ ./vcf.sh -- David < ~/documents/contacts/contacts.vcf
./vcf.sh: line 70: $1: unbound variable
and I'm stumped!

**Comment by l0b0** [comment]
Thanks for the tip! I had botched up the documentation, and the error handling didn't detect the missing parameter properly.

**Comment by linuxcaffe** [comment]
Yup! that works! thanks!
