### ISSUE TITLE
"vcf -p" pretty-print output

### ISSUE THREAD

**Issue by linuxcaffe** [l0b0/vcf#2]
vcf output would be more readable (useful) if it were "pretty-printed", removing all unnecessary elements, adding space between cards. so with command 

<pre>
./vcf.sh -p gump ~/contacts/*.vcf
</pre>

turns this;

<pre>
BEGIN:VCARD
VERSION:3.0
N:Gump;Forrest;;Mr.
FN:Forrest Gump
ORG:Bubba Gump Shrimp Co.
TITLE:Shrimp Man
PHOTO;VALUE=URL;TYPE=GIF:http://www.example.com/dir_photos/my_photo.gif
TEL;TYPE=WORK,VOICE:(111) 555-1212
TEL;TYPE=HOME,VOICE:(404) 555-1212
ADR;TYPE=WORK:;;100 Waters Edge;Baytown;LA;30314;United States of America
LABEL;TYPE=WORK:100 Waters Edge\nBaytown, LA 30314\nUnited States of America
ADR;TYPE=HOME:;;42 Plantation St.;Baytown;LA;30314;United States of America
LABEL;TYPE=HOME:42 Plantation St.\nBaytown, LA 30314\nUnited States of America
EMAIL;TYPE=PREF,INTERNET:forrestgump@example.com
REV:2008-04-24T19:52:43Z
END:VCARD
</pre>

into this:

<pre>
Forrest Gump
Bubba Gump Shrimp Co.
Shrimp Man
photo: http://www.example.com/dir_photos/my_photo.gif
work voice phone: (111) 555-1212
home voice phone: (404) 555-1212
work address: 100 Waters Edge, Baytown, LA, 30314, United States of America
home address: 42 Plantation St, Baytown, LA, 30314, United States of America
email: forrestgump@example.com
</pre>

**Comment by l0b0** [comment]
This is outside the scope of the program as it currently works (and I wouldn't use it like that). But you're free to implement it like this (possibly using a separate file with `sed` commands), and I'd merge it if it was properly tested.
