### ISSUE TITLE
'vcf -g string' to "grep" results

### ISSUE THREAD

**Issue by linuxcaffe** [l0b0/vcf#5]
To reduce the output to field names matching $string, the "-g" option to grep (or sed, or whatever) displaying only lines with matching fields.

<pre>
./vcf -g tel jane ~/contacts/*.vcf
</pre>

just shows

<pre>
work voice phone: (111) 555-1212

home voice phone: (404) 555-1212
</pre>

**Comment by l0b0** [comment]
You can achieve this by using `./vcf jane ~/contacts/*.vcf | grep ^TEL`. Other than that it's outside of my scope for the command, but as always you're welcome to implement it.
