### ISSUE TITLE
'vcf -G string' to "grep" results, also showing identifying fields 

### ISSUE THREAD

**Issue by linuxcaffe** [l0b0/vcf#6]
To reduce the output to field names matching $string, the "-G" option to grep (or sed, or whatever) displaying only lines with matching fields, but unlike the "-g" option (issue #5) "-G" also shows the identifying fields FN: and ORG:
so then

<pre>
./vcf -G tel jane ~/contacts/*.vcf
</pre>

shows (if it were pretty-printed, like #2)

<pre>
Tarzan U. Jane
Jungle inc
work voice phone: (111) 555-1212

Janet Dammit
home voice phone: (404) 555-1212
</pre>

**Comment by l0b0** [comment]
Again outside my scope for the command, but you're welcome to implement it. You can also achieve the same with `./vcf.sh jane ~/contacts/*.vcf | grep -E '^(FN|ORG|TEL)'`.

**Comment by linuxcaffe** [comment]
Thanks a bunch for pointing out the worarounds for these spurious issues. I can deal with that. 
You can't blame a guy for trying ;-)
