### ISSUE TITLE
filter not working on vcard files with spaces

### ISSUE THREAD

**Issue by linuxcaffe** [l0b0/vcf#7]
vcf is working great for two of my contact lists, but I have a vcard file with spaces (blank lines) in between "cards", and vcf fails to apply a filter to that file, just displays the whole file.

**Comment by l0b0** [comment]
It is rather picky, but anything that validates with the [vCard validator](https://pypi.python.org/pypi/vcard) should be parsed properly. Making it less picky is the same rabbit hole browser developers dug themselves into in the nineties.
