### ISSUE TITLE
add install docs for git-includes

### ISSUE THREAD

**Issue by linuxcaffe** [l0b0/vcf#8]
It would be great if you included a note in the README with a brief explanation on how to use git-includes; I hadn't encountered them before, got guidance via IRC on how to update them, now I forget ;-) This would be helpful for other git-n00bs too. (after researching it) Maybe suggesting;

<pre>
git clone --recursive https://github.com/l0b0/vcf.git
</pre>

?

**Comment by l0b0** [comment]
Good point, thanks!
